# List the basenames
BASENAMES = game_01 game_02 game_03 game_04 game_05 game_06 game_07 game_08

# Declare the extra dependencies for each .js that will be built
#
# ** DO NOT INCLUDE THE BASE .TS FILES **
game_01.js: ./common.ts
game_02.js: ./common.ts
game_03.js: ./common.ts
game_04.js: ./common.ts
game_05.js: ./common.ts
game_06.js: ./common.ts
game_07.js: ./common.ts
game_08.js: ./common.ts

# Include the common makefile, it does the rest
include ../../common.mk
