# List the basenames
BASENAMES = game_00 game_01 game_02 game_03 game_04

# Declare the extra dependencies for each .js that will be built
#
# ** DO NOT INCLUDE THE BASE .TS FILES **
game_00.js:
game_01.js:
game_02.js:
game_03.js:
game_04.js:

# Include the common makefile, it does the rest
include ../../common.mk
