# List the basenames
BASENAMES = game_01 game_02 game_03 game_04 game_05 game_06 game_07 game game_09

# Declare the extra dependencies for each .js that will be built
#
# ** DO NOT INCLUDE THE BASE .TS FILES **
game_01.js:
game_02.js:
game_03.js:
game_04.js:
game_05.js:
game_06.js:
game_07.js:
game.js:
game_09.js:

# Include the common makefile, it does the rest
include ../../common.mk
