# List the basenames
BASENAMES = game_01

# Declare the extra dependencies for each .js that will be built
#
# ** DO NOT INCLUDE THE BASE .TS FILES **
game_01.js:

# Include the common makefile, it does the rest
include ../../common.mk
