# List the basenames
BASENAMES = game_08 game_09 game_10 game_11 game_12 game_13 game_14

# Declare the extra dependencies for each .js that will be built
#
# ** DO NOT INCLUDE THE BASE .TS FILES **
game_08.js:
game_09.js:
game_10.js:
game_11.js: ./common.ts
game_12.js: ./common.ts
game_13.js: ./common.ts
game_14.js: ./common.ts

# Include the common makefile, it does the rest
include ../../common.mk
