# List the basenames
BASENAMES = game_15 game_16

# Declare the extra dependencies for each .js that will be built
#
# ** DO NOT INCLUDE THE BASE .TS FILES **
game_15.js: ./common.ts
game_16.js: ./common.ts

# Include the common makefile, it does the rest
include ../../common.mk
