# List the basenames
BASENAMES = game_01 game_02

# Declare the extra dependencies for each .js that will be built
#
# ** DO NOT INCLUDE THE BASE .TS FILES **
game_01.js: ./common.ts ./filters.ts
game_02.js: ./common.ts ./filters.ts

# Include the common makefile, it does the rest
include ../../common.mk
