# List the basenames
BASENAMES = game

# Declare the extra dependencies for each .js that will be built
#
# ** DO NOT INCLUDE THE BASE .TS FILES **
game.js: ./common.ts ./chooser.ts ./help.ts ./main.ts ./splash.ts

# Include the common makefile, it does the rest
include ../../common.mk
